### ISSUE TITLE
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine

### ISSUE THREAD

**Issue by henryliuom** [yeasy/hyperledger-py#16]
I installed the hyperledger by pip install command,and run the code:
>>> from hyperledger.client import Client
>>> c = Client(base_url="http://localhost:7050")
>>> c.chain_list()

but i got the error:
Traceback (most recent call last):
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/root/.pyenv/versions/3.6.2/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/root/.pyenv/versions/3.6.2/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/root/.pyenv/versions/3.6.2/lib/python3.6/http/client.py", line 279, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine:  
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/root/.pyenv/versions/3.6.2/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/root/.pyenv/versions/3.6.2/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/root/.pyenv/versions/3.6.2/lib/python3.6/http/client.py", line 279, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\n',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/hyperledger/api/blockchain.py", line 31, in chain_list
    res = self._get(self._url("/chain"))
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/hyperledger/utils/decorators.py", line 29, in inner
    return f(self, *args, **kwargs)
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/hyperledger/client.py", line 87, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/root/.pyenv/versions/env362/lib/python3.6/site-packages/requests-2.18.4-py3.6.egg/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\n',))

my,fabric version is 1.0 and python version is 3.6.2, how to dear this error?thanks.

**Comment by yeasy** [comment]
the project has been migrated to github.com/hyperledger/fabric-sdk-py.

**Comment by henryliuom** [comment]
thanks,i've installed fabric-sdk-py,how to use in fabric-sdk-py?i can't find the document for use.would you give me the example like this:
>>> from hyperledger.client import Client
>>> c = Client(base_url="http://127.0.0.1:7050")
>>> c.peer_list()

thanks
