### ISSUE TITLE
Unable to import hyperledger.client - dependency on sslAdapter.

### ISSUE THREAD

**Issue by ProgramErgoSum** [yeasy/hyperledger-py#6]
Hi,
I am stuck at this point. Can you please tell me, how to get around this?

```
>>> from hyperledger.client import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/hyperledger/__init__.py", line 19, in <module>
    from .client import Client, from_env  # flake8: noqa
  File "/usr/local/lib/python2.7/dist-packages/hyperledger/client.py", line 24, in <module>
    from .utils import update_headers, kwargs_from_env
  File "/usr/local/lib/python2.7/dist-packages/hyperledger/utils/__init__.py", line 13, in <module>
    from .utils import (
  File "/usr/local/lib/python2.7/dist-packages/hyperledger/utils/utils.py", line 27, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/hyperledger/tls.py", line 17, in <module>
    from .ssladapter import SSLAdapter
ImportError: No module named ssladapter

```

**Comment by yeasy** [comment]
Thanks for the reporting.
Can u provide the method to repeat?
Did u install from source-code or from pip?
Thanks!

**Comment by ProgramErgoSum** [comment]
It was installed from `pip` as 
`sudo pip install hyperledger --upgrade`

**Comment by yeasy** [comment]
I've uploaded a new 0.1.4 version, can u try it?

**Comment by ProgramErgoSum** [comment]
It works! Thanks for the quick fix.
